version: '3.9'

services:
  backend:
    build: ./BackEnd
    container_name: athenia-backend
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/app
    env_file:
      - ./BackEnd/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always

  frontend:
    build: ./FrontEnd
    container_name: athenia-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always
